### ISSUE TITLE
CLI: Twitter Analytics 

### ISSUE THREAD

**Issue by cyri113** [TogetherCrew/twitter-bot#14]
In order to complete the project, we must build a script where:

1. The user is asked to enter a Twitter handle
2. The script then completes the extraction
3. The script outputs the results of the neo4j analytics queries

To accomplish list we must:

1. Create a `docker-compose.yml` file that the user can run user
2. Create a script `cli.py` that gets the user handle and creates + launches the saga
3. The script should check every x seconds on the status of the saga
4. When the saga completes, it should run the neo4j analytics queries (currently on the api)
5. It should print out the results to the cli.

**Comment by amindadgar** [comment]
First, could you tell me what the use case would be? (so I would adapt the answer below to the most suitable answer to our use-case)

I can see the things to be done are
1. Add logs for tweet extraction (the tweet saving does have logs)
2. To create a file named `main.py` that would run all the transactions in order.

Estimation time to do this: less than 3 hours.
